#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# BSD ls colors
export LSCOLORS='ExGxCxDxCxegedabagacad'

# BSD ls options
alias ls='ls -FG'

# GNU ls colors
export LS_COLORS="di=34;01:ln=36;01:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07"

# Zsh completion colors
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# PATH
# export PATH=~/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.3/bin:/Library/Frameworks/Python.framework/Versions/3.2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin
export PATH=~/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.6/bin:/Library/Frameworks/Python.framework/Versions/2.5/bin:/Library/Frameworks/Python.framework/Versions/2.4/bin:/Library/Frameworks/Python.framework/Versions/3.1/bin:/Library/Frameworks/Python.framework/Versions/3.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin
# CDPATH
export CDPATH=.:~/dev/surveymonkey:~/dev/git-repos:~/dev/hg-repos

# OpenStack
if [ -f ~/.web-openrc.sh ]; then
  . ~/.web-openrc.sh
fi

# Python pip
export PIP_DOWNLOAD_CACHE=~/.pip/download-cache

# Make hub use HTTP instead of HTTPS
export HUB_TEST_HOST=code.corp.surveymonkey.com:80

# Python virtualenvwrapper
export WORKON_HOME=~/python/virtualenvs
if which virtualenvwrapper.sh > /dev/null; then
  source $(which virtualenvwrapper.sh)
fi

# If a virtualenv activated, reactivate to get its path mods back
if [ ! -z $VIRTUAL_ENV ]; then
  source $VIRTUAL_ENV/bin/activate
fi

if [ -f ${HOME}/devpi/bin/devpi-ctl ]; then
  alias devpi-ctl="${HOME}/devpi/bin/devpi-ctl"
fi

# export PYTHONSTARTUP=~/.pythonrc.py
# alias python='PYTHONSTARTUP=~/.pythonrc.py python'

alias gb='git branch -v'
alias gph='git push origin HEAD'
alias grls='git remote -v'
alias gwho='git shortlog -n -s --no-merges'
alias gws='git status --short --branch'
alias h='fc -i -D -l -1000000 | LESS="" less +G'
alias ipy='ipython'
alias mkve='mkvirtualenv'
alias pi='pip install'
pipun() {
  pip uninstall --verbose --yes "$@"
  if pip freeze | grep "$@"; then
    pip uninstall --verbose --yes "$@"
  fi
}
alias psd='pserve development.ini'
alias psdl='pserve development_local.ini'
alias py='python'
pys() {
  python -c 'import setuptools; execfile("setup.py")' "$@"
}
alias rerc='source ~/.zshrc'
alias sba='source bin/activate'

# Make Ctrl-Left and Ctrl-Right go backward/forward by words
# Sorin won't accept PR for prezto
# See: https://github.com/sorin-ionescu/prezto/issues/278
bindkey "^[[1;5D" emacs-backward-word
bindkey "^[[1;5C" emacs-forward-word

# Make up and down arrows only use local history
# (don't share history from other zsh sessions - e.g.: tabs)
# from http://superuser.com/questions/446594/separate-up-arrow-lookback-for-local-and-global-zsh-history
if [ ! -z "${key_info[Up]}" ]; then
  bindkey "${key_info[Up]}" up-line-or-local-history
fi
if [ ! -z "${key_info[Down]}" ]; then
  bindkey "${key_info[Down]}" down-line-or-local-history
fi

up-line-or-local-history() {
    zle set-local-history 1
    zle up-line-or-history
    zle set-local-history 0
}
zle -N up-line-or-local-history
down-line-or-local-history() {
    zle set-local-history 1
    zle down-line-or-history
    zle set-local-history 0
}
zle -N down-line-or-local-history

# Don't exit shell when hit Ctrl-D
setopt ignoreeof

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
