#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# BSD ls colors
export LSCOLORS='ExGxCxDxCxegedabagacad'

# BSD ls options
alias ls='ls -FG'

# GNU ls colors
export LS_COLORS="di=34;01:ln=36;01:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07"

# Zsh completion colors
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# PATH
export PATH=~/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

# Python pip
export PIP_DOWNLOAD_CACHE=~/.pip/download-cache

# Python virtualenvwrapper
export WORKON_HOME=~/python/virtualenvs
source $(which virtualenvwrapper.sh)

# export PYTHONSTARTUP=~/.pythonrc.py
alias python='PYTHONSTARTUP=~/.pythonrc.py python'

# Make Ctrl-Left and Ctrl-Right go backward/forward by words
# Sorin won't accept PR for prezto
# See: https://github.com/sorin-ionescu/prezto/issues/278
bindkey "^[[1;5D" emacs-backward-word
bindkey "^[[1;5C" emacs-forward-word
